import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  classesSidebar: [{
    type: 'doc',
    id: 'Classes/ARCamera',
    label: 'Classes'
  }],
  objectsSidebar: [{
    type: 'doc',
    id: 'Objects/100k',
    label: 'Objects'
  }],
  programmableSidebar: [{
   type: 'doc',
   id: 'Programmable Objects/ARController',
   label: 'Programmable Objects'
  }],
  modulesSidebar: [{
   type: 'doc',
   id: 'Modules',
   label: 'Modules'
  }],
  documentationSidebar: [
   {type: 'autogenerated', dirName: '.'}
  ]
};

export default sidebars;
